logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO


opensearch:
  url: https://localhost:9200

  authentication:
    certificate: localhost-18082.crt
    key: localhost-18082.key
    keypassword: 
    user: admin
    password: admin
