server:
  port: 9001

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO


opensearch:
  url: https://localhost:9200

  authentication:
    certificate: localhost-8443.crt
    key: localhost-8443.key
    keypassword: 
    user: admin
    password: admin
